// backend/src/users/users-fixture.service.ts
import { Injectable } from "@nestjs/common";
import { CreateUserInput, UsersService } from "./users.service";

type CreateFixtureUserOverrides = Partial<CreateUserInput>;

@Injectable()
export class UsersFixtureService {
    private sequence = 0;

    constructor(private readonly usersService: UsersService) {}

    private nextSequence() {
        this.sequence += 1;
        return this.sequence;
    }

    private generateUsername() {
        const seq = this.nextSequence();
        return `test_user_${Date.now()}_${seq}`;
    }

    private generatePassword() {
        return "123";
    }

    private generateRank() {
        return Math.floor(Math.random() * 1000);
    }

    private generateAbout() {
        const texts = [
            "Generated fixture user",
            "Temporary test profile",
            "Generated seed profile",
            "Autogenerated user data",
        ];

        return texts[Math.floor(Math.random() * texts.length)];
    }

    buildFixtureUserInput(overrides: CreateFixtureUserOverrides = {}): CreateUserInput {
        return {
            username: overrides.username ?? this.generateUsername(),
            plainPassword: overrides.plainPassword ?? this.generatePassword(),
            rank: overrides.rank ?? this.generateRank(),
            about: overrides.about ?? this.generateAbout(),
        };
    }

    async createTestUser(overrides: CreateFixtureUserOverrides = {}) {
        const input = this.buildFixtureUserInput(overrides);
        const created = await this.usersService.createUserRecord(input);

        return {
            id: String(created._id),
            username: created.username,
            plainPassword: input.plainPassword,
            rank: created.rank,
            about: created.about,
        };
    }

    async deleteUserById(userId: string) {
        return this.usersService.deleteUserById(userId);
    }

    async deleteUserByUsername(username: string) {
        return this.usersService.deleteUserByUsername(username);
    }
}