import { Injectable } from "@nestjs/common";
import { CreateUserInput, CreateUserOverrides } from "./users.types";
import { UserRole } from "./user-role.enum";

@Injectable()
export class UsersFactory {
    private sequence = 0;

    private nextSequence() {
        this.sequence += 1;
        return this.sequence;
    }

    private generateUsername() {
        const seq = this.nextSequence();
        return `test_user_${Date.now()}_${seq}`;
    }

    private generatePassword() {
        return "123";
    }

    private generateRank() {
        return Math.floor(Math.random() * 1000);
    }

    private generateAbout() {
        const texts = [
            "Generated fixture user",
            "Temporary test profile",
            "Generated seed profile",
            "Autogenerated user data",
        ];

        return texts[Math.floor(Math.random() * texts.length)];
    }

    buildCreateUserInput(overrides: CreateUserOverrides = {}): CreateUserInput & { role?: UserRole } {
        return {
            username: overrides.username ?? this.generateUsername(),
            plainPassword: overrides.plainPassword ?? this.generatePassword(),
            rank: overrides.rank ?? this.generateRank(),
            about: overrides.about ?? this.generateAbout(),
            role: overrides.role ?? UserRole.USER,
        };
    }
}